bongbu/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views, realty_news_views, realty_news_comment_views

app_name = 'bongbu'

urlpatterns = [
    # path('', views.index, name='index'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    # path('question/create/', views.question_create, name='question_create'),

    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),

    # realty_news_list.py
    path('realty_news_list', realty_news_views.realty_news_list, name='realty_news_list'),
    path('realty_news_list/<int:news_id>/', base_views.realty_news_detail, name='realty_news_detail'),
    path('realty_news_comment/create/<int:news_id>/', realty_news_comment_views.comment_create, name='comment_create'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from bongbu.views import base_views

urlpatterns = [
    path('bongbu/', include('bongbu.urls')),
    path('admin/', admin.site.urls),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

handler404 = base_views.page_not_found

bongbu/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

class Realty_News(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

class Realty_News_Comment(models.Model):
    news = models.ForeignKey(Realty_News, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

bongbu/forms.py
from django import forms
from bongbu.models import Question, Answer, Realty_News_Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
        }  

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

class Realty_News_Comment_Form(forms.ModelForm):
    class Meta:
        model = Realty_News_Comment
        fields = ['content']
        labels = {
            'content': '댓글내용',
        }

bongbu/views/answer_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import AnswerForm
from ..models import Question

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('bongbu:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'bongbu/question_detail.html', context)

bongbu/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404

from bongbu.models import Question, Realty_News
from django.db.models import Q
#zzz

def index(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) # 답변 내용 검색
        ).distinct()

    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'bongbu/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'bongbu/question_detail.html', context)

#부동산 뉴스 상세
def realty_news_detail(request, news_id):
    news = get_object_or_404(Realty_News, pk=news_id)
    context = {'news': news}
    return render(request, 'bongbu/realty_news_detail.html', context)

def page_not_found(request, exception):
    return render(request, 'common/404.html', {})

bongbu/views/question_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import QuestionForm
from ..models import Question


def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('bongbu:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'bongbu/question_form.html', context)

bongbu/views/realty_news_comment_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from ..forms import Realty_News_Comment_Form
from ..models import Realty_News

def comment_create(request, news_id):
    news = get_object_or_404(Realty_News, pk=news_id)
    if request.method == "POST":
        form = Realty_News_Comment_Form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.create_date = timezone.now()
            comment.news = news
            comment.save()
            return redirect('bongbu:realty_news_detail', news_id=news.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'news': news, 'form': form}
    return render(request, 'bongbu/realty_news_detail.html', context)

bongbu/views/realty_news_views.py
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.db.models import Q
from ..forms import QuestionForm
from ..models import Realty_News, Question


def realty_news_list(request):
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    realty_news_list = Realty_News.objects.order_by('-create_date')
    if kw:
        realty_news_list = realty_news_list.filter(
            Q(title__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(realty_news_comment__content__icontains=kw) # 댓글내용중에서 검색
        ).distinct()

    paginator = Paginator(realty_news_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'realty_news_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'bongbu/realty_news_list.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- bongbu CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, Bongbu!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/bongbu/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'bongbu:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/bongbu/question_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                    value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                        id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/bongbu/question_list.html
{% extends 'base.html' %}
{% load bongbu_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'bongbu:question_create' %}" class="btn btn-primary">질문 등록하기</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <!-- <td>{{ forloop.counter }}</td> -->
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'bongbu:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if question_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ question_list.previous_page_number }}"
               href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"
               href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
        {% if page_number == question_list.number %}
        <li class="page-item active" aria-current="page">
            <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
            <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
            <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if question_list.has_next %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a> -->
            <a class="page-link" data-page="{{ question_list.next_page_number }}"
                href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <!-- <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a> -->
            <a class="page-link" tabindex="-1" aria-disabled="true"
                href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'bongbu:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'index' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/bongbu/realty_news_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 타이틀 -->
    <h2 class="border-bottom py-2">{{ news.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <!-- <div class="card-text" style="white-space: pre-line;">{{ news.content }}</div> -->
            <div class="card-text" style="white-space: pre-line;">{{ news.content|safe }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ news.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 댓글 -->
    <h5 class="border-bottom my-3 py-2">{{news.realty_news_comment_set.count}}개의 댓글이 있습니다.</h5>
    {% for answer in news.realty_news_comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 댓글 등록 -->
    <form action="{% url 'bongbu:comment_create' news.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">댓글내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="댓글등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}

templates/bongbu/realty_news_list.html
{% extends 'base.html' %}
{% load bongbu_filter %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-6">
            <a href="{% url 'bongbu:question_create' %}" class="btn btn-primary">부동산 뉴스</a>
        </div>
        <div class="col-6">
            <div class="input-group">
                <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if realty_news_list %}
        {% for one_news in realty_news_list %}
        <tr>
            <!-- <td>{{ forloop.counter }}</td> -->
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ realty_news_list.paginator.count|sub:realty_news_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>
                <a href="{% url 'bongbu:realty_news_detail' one_news.id %}">{{ one_news.title }}</a>
                {% if one_news.realty_news_comment_set.count > 0 %}
                <span class="text-danger small mx-2">{{ one_news.realty_news_comment_set.count }}</span>
                {% endif %}
            </td>
            <td>{{ one_news.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if realty_news_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ realty_news_list.previous_page_number }}"
               href="javascript:void(0)">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true"
               href="javascript:void(0)">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in realty_news_list.paginator.page_range %}
        {% if page_number >= realty_news_list.number|add:-5 and page_number <= realty_news_list.number|add:5 %}
        {% if page_number == realty_news_list.number %}
        <li class="page-item active" aria-current="page">
            <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
            <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a> -->
            <a class="page-link" data-page="{{ page_number }}"
                href="javascript:void(0)">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if realty_news_list.has_next %}
        <li class="page-item">
            <!-- <a class="page-link" href="?page={{ realty_news_list.next_page_number }}">다음</a> -->
            <a class="page-link" data-page="{{ realty_news_list.next_page_number }}"
                href="javascript:void(0)">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <!-- <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a> -->
            <a class="page-link" tabindex="-1" aria-disabled="true"
                href="javascript:void(0)">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
    <a href="{% url 'bongbu:question_create' %}" class="btn btn-primary">질문 등록하기</a>
</div>
<form id="searchForm" method="get" action="{% url 'bongbu:realty_news_list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}

templates/navbar.html
<!-- 네비게이션바 -->
<!-- branch test -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'bongbu:index' %}">Bongbu</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bongbu:realty_news_list' %}">부동산 뉴스</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bongbu:question_create' %}">추천 경매물건</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bongbu:index' %}">분양정보</a>
                </li>
            </ul>
        </div>
    </div>
</nav>